services:
  - type: web
    name: hole-in-one-admin
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        sync: false 